version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: mariem
      POSTGRES_PASSWORD: secret
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  todo_pgdata:
