version: '3.8'
services:
  db:
    image: postgres:14
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: mariem
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - todo_pgdata:/var/lib/postgresql/data

volumes:
  todo_pgdata:
